<a href="https://colab.research.google.com/github/lavanyayada112/Fake--News-Detection-ML/blob/main/Fakenews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Machine learning fake news Detection projectss

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
true = pd.read_csv('True.csv')
fake = pd.read_csv('Fake.csv')

In [ ]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
true['label'] = 1

In [ ]:
fake['label'] = 0

In [ ]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [ ]:
news = pd.concat([fake , true],axis=0)

In [ ]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [ ]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [ ]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [ ]:
news = news.drop(['title', 'subject','date'],axis=1)

In [ ]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [ ]:
news = news.sample(frac=1)

In [ ]:
news.head()

                                                    text  label
16334  The woman s name is Denise Scott. You can dona...      0
710    After GOP Rep. Steve Scalise was shot during a...      0
20767  A Princeton professor gives viewers of FOX New...      0
18418  The Washington Post published a propaganda org...      0
2500   WASHINGTON (Reuters) - U.S. banking rules must...      1

In [ ]:
news.reset_index(inplace=True)

In [ ]:
news.head()

   index                                               text  label
0  16334  The woman s name is Denise Scott. You can dona...      0
1    710  After GOP Rep. Steve Scalise was shot during a...      0
2  20767  A Princeton professor gives viewers of FOX New...      0
3  18418  The Washington Post published a propaganda org...      0
4   2500  WASHINGTON (Reuters) - U.S. banking rules must...      1

In [ ]:
news.drop(['index'], axis=1, inplace=True)

In [ ]:
news.head()

                                                text  label
0  Every single day, liberals provide more and mo...      0
1  A sign on the door of a Kewaskum Dairy Queen, ...      0
2  (Reuters) - Republican presidential candidate ...      1
3  PARIS (Reuters) - Common sense is prevailing i...      1
4  This ll be about as bad as it s been in Seattl...      0

In [ ]:
import re

In [ ]:
def wordopt(text):
  #Convert into lowercase
    text = text.lower()

  #Remove URLs
    text = re.sub(r'https?://S+|www\.\S+',' ',text)

   # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    # Remove digits
    text = re.sub(r'\d', '', text)

    # Remove newline characters
    text = re.sub(r'\n', ' ', text)

    return text

In [ ]:
news['text'] = news['text'].apply(wordopt)

In [ ]:
news['text']

0        the woman s name is denise scott you can donat...
1        after gop rep steve scalise was shot during a ...
2        a princeton professor gives viewers of fox new...
3        the washington post published a propaganda org...
4        washington reuters  us banking rules must prot...
                               ...
44893    this is great trump supporters did everything ...
44894    the clinton grifters were fantastic mentors to...
44895    new york reuters  bernie sanders may have lost...
44896    new york reuters  the bill hillary  chelsea cl...
44897    st century wire says reframing the current dip...
Name: text, Length: 44898, dtype: object

In [ ]:
x = news['text']
y = news['label']

In [ ]:
x

0        the woman s name is denise scott you can donat...
1        after gop rep steve scalise was shot during a ...
2        a princeton professor gives viewers of fox new...
3        the washington post published a propaganda org...
4        washington reuters  us banking rules must prot...
                               ...
44893    this is great trump supporters did everything ...
44894    the clinton grifters were fantastic mentors to...
44895    new york reuters  bernie sanders may have lost...
44896    new york reuters  the bill hillary  chelsea cl...
44897    st century wire says reframing the current dip...
Name: text, Length: 44898, dtype: object

In [ ]:
y

0        0
1        0
2        0
3        0
4        1
        ..
44893    0
44894    0
44895    1
44896    1
44897    0
Name: label, Length: 44898, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
x_train.shape

(31428,)

In [ ]:
x_test.shape

(13470,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorization = TfidfVectorizer()

In [ ]:
xv_train = vectorization.fit_transform(x_train)

In [ ]:
xv_test = vectorization.transform(x_test)

In [ ]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6443184 stored elements and shape (31428, 177130)>

In [ ]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2740127 stored elements and shape (13470, 177130)>

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
LR = LogisticRegression()

In [ ]:
LR.fit(xv_train,y_train)

LogisticRegression()

In [ ]:
pred_lr=LR.predict(xv_test)

In [ ]:
LR.score(xv_test, y_test)

0.9870824053452116

In [ ]:
 from sklearn.metrics import classification_report
 print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6988
           1       0.98      0.99      0.99      6482

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier()
DTC.fit(xv_train, y_train)

DecisionTreeClassifier()

In [ ]:
pred_dtc = DTC.predict(xv_test)

In [ ]:
DTC.score(xv_test, y_test)

0.9952487008166295

In [ ]:
print(classification_report(y_test, pred_dtc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      6988
           1       0.99      1.00      1.00      6482

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(xv_train, y_train)

RandomForestClassifier()

In [ ]:
predict_rfc = rfc.predict(xv_test)

In [ ]:
rfc.score(xv_test, y_test)

0.9849294729027468

In [ ]:
print(classification_report(y_test, predict_rfc))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      6988
           1       0.98      0.99      0.98      6482

    accuracy                           0.98     13470
   macro avg       0.98      0.98      0.98     13470
weighted avg       0.98      0.98      0.98     13470

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()
gbc.fit(xv_train, y_train)

GradientBoostingClassifier()

In [ ]:
pred_gbc =gbc.predict(xv_test)

In [ ]:
gbc.score(xv_test, y_test)

0.9961395694135116

In [ ]:
print(classification_report(y_test, pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      6988
           1       0.99      1.00      1.00      6482

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [ ]:
def output_lable(n):
    if n == 0:
        return "It is a Fake News"
    elif n == 1:
        return "It is a Genuine News"

In [ ]:
def manual_testing(news):
    testing_news = {"text": [news]}  # Corrected syntax for defining dictionary
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)  # Assuming 'vectorization' is your vectorizer object

    pred_lr = LR.predict(new_xv_test)
    # pred_dtc = dtc.predict(new_xv_test)
    pred_gbc = gbc.predict(new_xv_test)
    pred_rfc = rfc.predict(new_xv_test)

    return "\n\nLR Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(
        output_label(pred_lr[0]),output_label(pred_gbc[0]), output_label(pred_rfc[0]))

In [ ]:


news_article = str(input())



In [ ]:
manual_testing(news_article)

NameError: name 'output_label' is not defined